#!/usr/bin/env python3
"""S8's browser-level check: the DEFENDER's pre-battle choice, in two clients.

Why this exists. The owner hit this LIVE, mid-game, in a two-browser game: he
clicked "Fight!" and got the battleground immediately, while the other player was
never offered the chance to give up. A DOM-free suite cannot see "whose client
shows which button"; this check drives the REAL built app in headless Chrome
against a fake ServerStore on the same origin, one browser per SEAT, and reads
the DOM the owner watches.

What it proves, mode by mode:

  host (seat 0, the ATTACKER — the mover whose Turn it is)
   1. the app resumes the game and the board renders;
   2. pressing "Start engagement" opens the engagement and the overlay appears;
   3. the attacker's overlay says it is WAITING on the defender and offers NO
      battle button — the exact button that stole the defender's decision;
   4. a force-dispatched `proposeAgreement{fight}` (the removed code path) is
      REFUSED: the phase stays `Fight`, no battle exists, and nothing is
      published to the store;
   5. the engagement window is the defender's, so the attacker's own Flee is
      never offered either.

  guest (seat 1, the DEFENDER)
   6. the defender's client is the one asked: "Stand and fight" and "Flee" are
      both on screen, and no battle button is;
   7. the defender is told it is the attacker's legion attacking;
   8. once the defender stands, the window closes for the whole table — the
      client's own overlay now offers the battle, and the state it holds says
      `fleeDeclined`, so a battle can begin;
   9. the resolution is PUBLISHED (the defender's answer reaches the attacker's
      client through the store, as the app's ONE commit path does it).

No key material is used (the keys are made-up strings containing `testonly`) and
no request leaves this box. The Chrome tree is killed in `finally`, success and
failure alike.

Run it after a subpath-free build:

  (cd web && npx vitest run --config scripts/browser-check/vitest.config.s8.ts)
  (cd web && VITE_SERVERSTORE_URL=/storeapi npx vite build \\
      --outDir ../scripts/browser-check/s8-dist --emptyOutDir)
  python3 scripts/browser-check/s8-engagement-choice.py host
  python3 scripts/browser-check/s8-engagement-choice.py guest

The fixture (`scripts/browser-check/s8-fixture.json`) is GENERATED by the real
engine and is gitignored scratch.
"""

import argparse
import base64
import functools
import hashlib
import http.server
import json
import os
import shutil
import socket
import subprocess
import sys
import threading
import time
import urllib.parse
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
DIST = os.environ.get("S8_SITE", os.path.join(HERE, "s8-dist"))
PROFILE = os.path.join(HERE, "s8-profile")
FIXTURE = os.environ.get("S8_FIXTURE", os.path.join(HERE, "s8-fixture.json"))
KEY_KEY = "colossusweb.key.v1"
ACTIVE_KEY = "colossusweb.multiplayer.v1"
SAVE_KEY = "colossusweb.save.v1"
# Made-up keys whose `_testonly` marker keeps the fake store's identity split.
SEAT0_KEY = "ssk_FPYGNDslev_p_testonlysecret"  # host id -> FPYGNDslev_p
SEAT1_KEY = "ssk_i9PGQ7wIj971_testonlysecret"  # guest id -> i9PGQ7wIj971

with open(FIXTURE, "r", encoding="utf8") as fh:
    FX = json.load(fh)
GAME = FX["gameId"]
SNAP_PREFIX = "snap.%s." % GAME


class Store:
    """The fake ServerStore: name -> body, plus every PUT the app made."""

    def __init__(self, bodies):
        self.objects = dict(bodies)
        self.puts = []

    def put(self, name, body):
        self.objects[name] = body
        self.puts.append({"name": name, "body": json.loads(body)})

    def listing(self, prefix):
        out = []
        for name, body in sorted(self.objects.items()):
            if prefix and not name.startswith(prefix):
                continue
            data = body.encode()
            out.append(
                {
                    "store": "colossus",
                    "name": name,
                    "sha256": hashlib.sha256(data).hexdigest(),
                    "size": len(data),
                    "createdAt": "2026-09-29T10:00:00.000Z",
                }
            )
        return out


STORE = None
REQUEST_LOG = []


class Handler(http.server.BaseHTTPRequestHandler):
    def log_message(self, *args):
        pass

    def _send(self, code, body, ctype="application/json", extra=None):
        REQUEST_LOG.append("%s %s -> %s" % (self.command, self.path, code))
        data = body.encode() if isinstance(body, str) else body
        self.send_response(code)
        self.send_header("content-type", ctype)
        self.send_header("content-length", str(len(data)))
        for key, value in (extra or {}).items():
            self.send_header(key, value)
        self.end_headers()
        self.wfile.write(data)

    def do_OPTIONS(self):
        self._send(
            204,
            "",
            extra={
                "access-control-allow-origin": "*",
                "access-control-allow-methods": "GET, PUT, DELETE, OPTIONS",
                "access-control-allow-headers": "authorization, content-type",
            },
        )

    def do_GET(self):
        if self.path.startswith("/storeapi"):
            return self.api("GET")
        path = self.path.split("?")[0]
        if path == "/":
            path = "/index.html"
        target = os.path.normpath(os.path.join(DIST, path.lstrip("/")))
        if not target.startswith(DIST) or not os.path.isfile(target):
            return self._send(404, "not found", "text/plain")
        ctype = {
            ".html": "text/html",
            ".js": "application/javascript",
            ".css": "text/css",
            ".json": "application/json",
        }.get(os.path.splitext(target)[1], "application/octet-stream")
        with open(target, "rb") as fh:
            return self._send(200, fh.read(), ctype)

    def do_PUT(self):
        return self.api("PUT")

    def do_DELETE(self):
        return self.api("DELETE")

    def do_POST(self):
        return self.api("POST")

    def api(self, method):
        auth = self.headers.get("authorization") or ""
        key = auth.replace("Bearer ", "")
        identity = (
            key.split("_testonly")[0].replace("ssk_", "") if "_testonly" in key else "FPYGNDslev_p"
        )
        path = self.path.split("?")[0][len("/storeapi") :]
        query = {}
        if "?" in self.path:
            for pair in self.path.split("?", 1)[1].split("&"):
                if "=" in pair:
                    k, v = pair.split("=", 1)
                    query[k] = urllib.parse.unquote(v)
        if path == "/whoami":
            return self._send(
                200,
                json.dumps(
                    {
                        "id": identity,
                        "label": "Host" if identity.startswith("FPY") else "Guest",
                        "stores": ["colossus"],
                        "perms": ["read", "write"],
                    }
                ),
            )
        if path.startswith("/stores/colossus/objects"):
            rest = path[len("/stores/colossus/objects") :].lstrip("/")
            if not rest:
                return self._send(
                    200, json.dumps({"objects": STORE.listing(query.get("prefix", ""))})
                )
            name = urllib.parse.unquote(rest)
            if method == "GET":
                if name not in STORE.objects:
                    return self._send(
                        404, json.dumps({"error": {"code": "not_found", "message": name}})
                    )
                body = STORE.objects[name]
                sha = hashlib.sha256(body.encode()).hexdigest()
                return self._send(200, body, extra={"x-serverstore-sha256": sha})
            if method == "PUT":
                length = int(self.headers.get("content-length") or 0)
                body = self.rfile.read(length).decode()
                STORE.put(name, body)
                data = body.encode()
                return self._send(
                    200,
                    json.dumps(
                        {
                            "store": "colossus",
                            "name": name,
                            "sha256": hashlib.sha256(data).hexdigest(),
                            "size": len(data),
                            "createdAt": "2026-09-29T10:00:00.000Z",
                        }
                    ),
                )
        return self._send(404, json.dumps({"error": {"code": "not_found", "message": path}}))


class WS:
    """A minimal DevTools-Protocol client (its own WebSocket; no library)."""

    def __init__(self, url):
        self.url, self.buf, self.next_id = url, b"", 1

    def connect(self):
        rest = self.url.split("://", 1)[1]
        hostport, path = rest.split("/", 1)
        host, port = hostport.split(":")
        self.sock = socket.create_connection((host, int(port)), timeout=10)
        key = base64.b64encode(os.urandom(16)).decode()
        self.sock.sendall(
            (
                "GET /%s HTTP/1.1\r\nHost: %s\r\nUpgrade: websocket\r\n"
                "Connection: Upgrade\r\nSec-WebSocket-Key: %s\r\nSec-WebSocket-Version: 13\r\n\r\n"
                % (path, hostport, key)
            ).encode()
        )
        data = b""
        while b"\r\n\r\n" not in data:
            data += self.sock.recv(4096)
        assert b"101" in data.split(b"\r\n")[0], data[:200]

    def send(self, text):
        payload, mask = text.encode(), os.urandom(4)
        n = len(payload)
        if n < 126:
            header = bytes([0x81, 0x80 | n])
        elif n < 65536:
            header = bytes([0x81, 0x80 | 126]) + n.to_bytes(2, "big")
        else:
            header = bytes([0x81, 0x80 | 127]) + n.to_bytes(8, "big")
        self.sock.sendall(header + mask + bytes(b ^ mask[i % 4] for i, b in enumerate(payload)))

    def _read(self, n):
        while len(self.buf) < n:
            chunk = self.sock.recv(65536)
            if not chunk:
                raise ConnectionError("closed")
            self.buf += chunk
        out, self.buf = self.buf[:n], self.buf[n:]
        return out

    def recv(self):
        while True:
            b0, b1 = self._read(2)
            op, ln = b0 & 0x0F, b1 & 0x7F
            if ln == 126:
                ln = int.from_bytes(self._read(2), "big")
            elif ln == 127:
                ln = int.from_bytes(self._read(8), "big")
            payload = self._read(ln)
            if op == 0x8:
                raise ConnectionError("closed")
            if op == 0x1:
                return payload.decode()

    def call(self, method, params=None):
        mid = self.next_id
        self.next_id += 1
        self.send(json.dumps({"id": mid, "method": method, "params": params or {}}))
        while True:
            msg = json.loads(self.recv())
            if msg.get("id") == mid:
                return msg


def free_port():
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


class App:
    """The DOM reads the check is built on — every statement is one of these."""

    def __init__(self, ws):
        self.ws = ws

    def ev(self, expr):
        r = self.ws.call(
            "Runtime.evaluate", {"expression": expr, "returnByValue": True, "awaitPromise": True}
        )
        res = r.get("result", {})
        if "exceptionDetails" in res:
            return {"__error__": str(res["exceptionDetails"])[:300]}
        return res.get("result", {}).get("value")

    def center(self, selector_js):
        return self.ev(
            "(() => { const el = %s; if (!el) return null;"
            " const r = el.getBoundingClientRect();"
            " return JSON.stringify({x: Math.round(r.left + r.width/2), y: Math.round(r.top + r.height/2)}); })()"
            % selector_js
        )

    def real_click(self, selector_js):
        c = self.center(selector_js)
        if c is None:
            return False
        pt = json.loads(c)
        for t in ("mousePressed", "mouseReleased"):
            self.ws.call(
                "Input.dispatchMouseEvent",
                {"type": t, "x": pt["x"], "y": pt["y"], "button": "left", "clickCount": 1},
            )
            time.sleep(0.08)
        return True

    def click_button(self, label):
        """Press the button whose trimmed text is exactly `label`."""
        return self.ev(
            "(() => { const b=[...document.querySelectorAll('.board-decision-overlay button')]"
            " .find(b => (b.textContent||'').trim() === %s);"
            " if (!b) return false; b.click(); return true; })()" % json.dumps(label)
        )

    def button_labels(self):
        return self.ev(
            "JSON.stringify([...document.querySelectorAll('.board-decision-overlay button')]"
            ".map(b => (b.textContent||'').trim()))"
        )

    def card_text(self):
        return self.ev(
            "(document.querySelector('.board-decision-overlay')||{}).textContent || ''"
        )

    def message(self):
        return self.ev("(document.querySelector('.message')||{}).textContent || ''")

    def saved_state(self):
        raw = self.ev("localStorage.getItem(%s)" % json.dumps(SAVE_KEY))
        if not raw:
            return None
        try:
            blob = json.loads(raw)
        except Exception:
            return None
        return blob.get("state")

    def wait_for(self, expr, timeout=30, what=""):
        deadline = time.time() + timeout
        while time.time() < deadline:
            if self.ev(expr):
                return True
            time.sleep(0.25)
        raise AssertionError("timed out waiting for %s" % (what or expr))


class Check:
    def __init__(self, label):
        self.label = label
        self.failures = []
        self.count = 0

    def ok(self, name, cond, detail=""):
        self.count += 1
        tag = "PASS" if cond else "FAIL"
        line = "%s %s" % (tag, name)
        if not cond and detail:
            line += " — %s" % detail
        print(line)
        sys.stdout.flush()
        if not cond:
            self.failures.append((name, detail))


def snapshots():
    return [p for p in STORE.puts if p["name"].startswith(SNAP_PREFIX)]


def run(check, mode):
    global STORE

    bodies = {
        "%s" % FX["pendingSnapshotName"]: FX["pendingSnapshot"],
        "%s" % FX["openedSnapshotName"]: FX["openedSnapshot"],
        "game.%s" % GAME: FX["records"]["game"],
        "player.%s.%s" % (GAME, FX["host"]["tag"]): FX["records"]["players"][0],
        "player.%s.%s" % (GAME, FX["guest"]["tag"]): FX["records"]["players"][1],
    }
    if mode == "host":
        # The ATTACKER's client resumes on the PENDING state and opens the
        # engagement with its own control — the owner's real path. (The `opened`
        # snapshot is the guest run's seed; leaving it in would make the app
        # adopt it immediately and there would be nothing to open.)
        bodies.pop(FX["openedSnapshotName"])
    else:
        # The defender's client is seeded with the engagement ALREADY OPEN: that
        # is the moment its own window must be on screen. The older `pending`
        # snapshot is dropped so the app adopts the open one.
        bodies.pop(FX["pendingSnapshotName"])
    STORE = Store(bodies)

    site_port = free_port()
    httpd = http.server.ThreadingHTTPServer(("127.0.0.1", site_port), Handler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    cdp_port = free_port()
    shutil.rmtree(PROFILE, ignore_errors=True)
    log = open(os.path.join(HERE, "s8-chrome.log"), "w")
    chrome = subprocess.Popen(
        [
            "google-chrome",
            "--headless=new",
            "--disable-gpu",
            "--no-sandbox",
            "--hide-scrollbars",
            "--disable-dev-shm-usage",
            "--force-prefers-reduced-motion",
            "--user-data-dir=%s" % PROFILE,
            "--window-size=1600,1200",
            "--remote-debugging-port=%d" % cdp_port,
            "about:blank",
        ],
        stdout=log,
        stderr=log,
        start_new_session=True,
    )
    try:
        ws_url = None
        for _ in range(150):
            try:
                with urllib.request.urlopen(
                    "http://127.0.0.1:%d/json/list" % cdp_port, timeout=1
                ) as r:
                    page = next((t for t in json.load(r) if t.get("type") == "page"), None)
                if page:
                    ws_url = page["webSocketDebuggerUrl"]
                    break
            except Exception:
                time.sleep(0.2)
        assert ws_url, "no page target"
        ws = WS(ws_url)
        ws.connect()
        for m in ("Runtime.enable", "Page.enable", "Network.enable"):
            ws.call(m)
        seat_key = SEAT1_KEY if mode == "guest" else SEAT0_KEY
        ws.call(
            "Page.addScriptToEvaluateOnNewDocument",
            {
                "source": (
                    "try { localStorage.clear();"
                    " localStorage.setItem('%s', '%s');"
                    " localStorage.setItem('%s', JSON.stringify({version:1, gameId:'%s'}));"
                    " } catch (e) {}"
                )
                % (KEY_KEY, seat_key, ACTIVE_KEY, GAME)
            },
        )
        app = App(ws)
        ws.call("Page.navigate", {"url": "http://127.0.0.1:%d/index.html" % site_port})
        app.wait_for("!!document.querySelector('.lobby-panel')", 25, "lobby")
        # The Enter-game button is disabled while the lobby refreshes, and a click
        # on a disabled button is a silent no-op — retry until the board renders.
        deadline = time.time() + 45
        while time.time() < deadline and not app.ev("!!document.querySelector('svg.master-board')"):
            app.ev(
                "(() => { const b=[...document.querySelectorAll('button')]"
                ".find(b=>b.textContent.includes('Enter game'));"
                " if (b && !b.disabled) { b.click(); return true; } return false; })()"
            )
            time.sleep(1.0)
        if not app.ev("!!document.querySelector('svg.master-board')"):
            print("DEBUG after Enter game: %r" % (app.ev("document.body.innerText") or "")[:800])
            print("DEBUG requests: %r" % REQUEST_LOG[-15:])
            raise AssertionError("could not enter the game (board never rendered)")
        time.sleep(1.5)
        if mode == "host":
            host_statements(check, app)
        else:
            guest_statements(check, app)
    finally:
        try:
            os.killpg(os.getpgid(chrome.pid), 15)
        except Exception:
            pass
        try:
            chrome.wait(timeout=8)
        except Exception:
            try:
                os.killpg(os.getpgid(chrome.pid), 9)
            except Exception:
                pass
        httpd.shutdown()
        log.close()
        shutil.rmtree(PROFILE, ignore_errors=True)


HOST_MARKER = FX["attackerMarkerId"]
GUEST_MARKER = FX["defenderMarkerId"]


def overlay_present(app):
    return bool(app.ev("!!document.querySelector('.board-decision-overlay')"))


def host_statements(check, app):
    check.ok("the app resumed the game and rendered the board", bool(app.ev("!!document.querySelector('svg.master-board')")))
    check.ok(
        "the mover's own legion is on the board",
        bool(app.ev("!!document.querySelector('[data-legion=\"%s\"]')" % FX["attackerLegionId"])),
    )

    # The engagement is PENDING: press the app's own control to open it — the
    # click the owner made before he "clicked on fight". The control renders the
    # two marker chits (`fight-btn`), not the words.
    before = len(snapshots())
    opened = app.ev(
        "(() => { const b=document.querySelector('button.fight-btn');"
        " if (!b) return null; b.click(); return (b.textContent||'').trim(); })()"
    )
    check.ok(
        "there is a pending engagement to open",
        opened is not None,
        "fight-btn=%r body=%r" % (opened, (app.ev("document.body.innerText") or "")[:200]),
    )
    app.wait_for("!!document.querySelector('.board-decision-overlay')", 15, "the engagement overlay")
    time.sleep(0.6)

    labels = json.loads(app.button_labels() or "[]")
    text = app.card_text()
    published = snapshots()
    check.ok(
        "opening the engagement published exactly ONE snapshot",
        len(published) == before + 1,
        "PUTs %d -> %d" % (before, len(published)),
    )
    if published:
        opened_state = published[-1]["body"]["state"]["state"]
        check.ok(
            "the published state is the OPEN engagement, no battle",
            opened_state.get("battle") is None
            and (opened_state.get("activeEngagement") or {}).get("fleeDeclined") is False,
            "eng=%r battle=%r" % (opened_state.get("activeEngagement"), opened_state.get("battle")),
        )
    check.ok(
        "the ATTACKER's client says it is WAITING on the defender",
        "waiting for" in text.lower() and GUEST_MARKER in text,
        "text=%r" % text[:300],
    )
    check.ok(
        "the attacker's client offers NO battle button (the owner's bug)",
        "Fight!" not in labels,
        "labels=%r" % labels,
    )
    check.ok(
        "the attacker's client does not answer the defender's window either",
        "Stand and fight" not in labels and "Flee" not in labels,
        "labels=%r" % labels,
    )

    # THE regression: force the removed code path from the browser. `apply` is
    # the app's ONE commit path, so this is exactly the command the old button
    # dispatched — and it must be refused without starting a battle.
    before = len(snapshots())
    forced = app.ev(
        "(() => { if (typeof window.__colossusDispatch !== 'function') return 'no-handle';"
        " window.__colossusDispatch({type:'proposeAgreement', kind:'fight'}); return 'dispatched'; })()"
    )
    if forced == "no-handle":
        check.ok(
            "the app exposes its ONE commit path for the check (S8 test handle)",
            False,
            "window.__colossusDispatch missing",
        )
    else:
        time.sleep(1.2)
        state = app.saved_state()
        overlay_battle = bool(
            app.ev("!!document.querySelector('.battle-board') || !!document.querySelector('svg.battle-board')")
        )
        check.ok(
            "a force-dispatched attacker FIGHT does NOT start a battle",
            state is not None
            and state.get("phase") == "Fight"
            and state.get("battle") is None
            and state.get("activeEngagement") is not None,
            "phase=%r battle=%r" % (state and state.get("phase"), state and state.get("battle")),
        )
        check.ok(
            "and the battle board is not shown",
            not overlay_battle,
            "battle board rendered=%r" % overlay_battle,
        )
        check.ok(
            "and the refusal is LOUD on the message surface, not a silent no-op",
            "not answered flee or fight" in (app.message() or "").lower(),
            "message=%r" % app.message(),
        )
        check.ok(
            "and what it published still has NO battle and an OPEN window "
            "(a refused command changes no game data)",
            bool(snapshots())
            and snapshots()[-1]["body"]["state"]["state"].get("battle") is None
            and (
                snapshots()[-1]["body"]["state"]["state"].get("activeEngagement") or {}
            ).get("fleeDeclined")
            is False,
            "newest=%r" % (snapshots()[-1]["body"]["state"]["state"].get("activeEngagement") if snapshots() else None),
        )
        check.ok(
            "the engagement is still open, still waiting on the defender",
            overlay_present(app) and "waiting for" in app.card_text().lower(),
            "card=%r" % app.card_text()[:200],
        )


def guest_statements(check, app):
    check.ok("the defender's client resumed the game and rendered the board", bool(app.ev("!!document.querySelector('svg.master-board')")))
    check.ok(
        "the engagement overlay is on the defender's screen",
        overlay_present(app),
        "body=%r" % (app.ev("document.body.innerText") or "")[:300],
    )

    labels = json.loads(app.button_labels() or "[]")
    text = app.card_text()
    check.ok(
        "the DEFENDER's client is the one asked to stand or flee",
        "Stand and fight" in labels and "Flee" in labels,
        "labels=%r" % labels,
    )
    check.ok(
        "the defender's client offers NO battle button",
        "Fight!" not in labels,
        "labels=%r" % labels,
    )
    check.ok(
        "the defender is told whose legion is attacking",
        "attacks with" in text,
        "text=%r" % text[:300],
    )

    # The defender answers: stand and fight.
    before = len(snapshots())
    clicked = app.click_button("Stand and fight")
    check.ok("the defender's 'Stand and fight' is pressable", clicked is True)
    time.sleep(1.5)

    state = app.saved_state()
    check.ok(
        "the defender's answer closes the window in the shared state",
        state is not None
        and state.get("activeEngagement") is not None
        and state["activeEngagement"].get("fleeDeclined") is True,
        "eng=%r" % (state and state.get("activeEngagement")),
    )
    check.ok(
        "no battle has started yet",
        state is not None and state.get("battle") is None and state.get("phase") == "Fight",
        "phase=%r battle=%r" % (state and state.get("phase"), state and state.get("battle")),
    )
    published = snapshots()
    check.ok(
        "the defender's answer is published for the attacker's client",
        len(published) == before + 1,
        "PUTs %d -> %d" % (before, len(published)),
    )
    if published:
        shared = published[-1]["body"]["state"]["state"]["activeEngagement"]
        check.ok(
            "the published snapshot carries the closed window",
            shared is not None and shared.get("fleeDeclined") is True,
            "published eng=%r" % shared,
        )
    labels_after = json.loads(app.button_labels() or "[]")
    check.ok(
        "with the window closed the defender has no window left to answer",
        "Stand and fight" not in labels_after and "Flee" not in labels_after,
        "labels=%r" % labels_after,
    )
    check.ok(
        "and the battle button is the ATTACKER's, so it is not on the defender's client",
        "Fight!" not in labels_after,
        "labels=%r" % labels_after,
    )


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("mode", choices=["host", "guest"])
    args = ap.parse_args()
    check = Check(args.mode)
    run(check, args.mode)
    print("\n%s: %d statements, %d failed" % (args.mode, check.count, len(check.failures)))
    if check.failures:
        for name, detail in check.failures:
            print("  FAILED: %s — %s" % (name, detail))
        sys.exit(1)
    print("%s: ALL STATEMENTS HELD" % args.mode)
    sys.exit(0)


if __name__ == "__main__":
    main()
